library(dplyr)
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip","archive.zip")
unzip("archive.zip")
file <- read.table(file="household_power_consumption.txt", sep=";", header=TRUE)
dateFrom <- as.Date("01/02/2007", format="%d/%m/%Y")
dateTo <- as.Date("02/02/2007", format="%d/%m/%Y")
file2<-file[between(as.Date(file$Date,"%d/%m/%Y"),dateFrom ,dateTo),]
png("plot1.png",width=480,height=480,units="px")
hist(as.numeric(as.character(file2$Global_active_power)),col="red",xlab="Global Active Power (kilowatts)",main="Global Active Power")
dev.off()